### ISSUE TITLE
Workload Deployments Fail

### ISSUE THREAD

**Issue by travishankins** [mspnp/fabrikam-dronedelivery-workload#14]
During our deployments (09-workload.md) we noticed that the delivery and ingestion helm chart deployments will fail due to the "ingress.hosts[0]" syntax.  

The error that we received was:  zsh: no matches found: ingress.hosts[0].name=dronedelivery.fabrikam.com"

Once we updated the helm package (Delivery and Ingestion Charts) to include quotes like below the issue was resolved: 

helm package ./charts/delivery/ -u
helm install delivery-v0.1.0-dev delivery-v0.1.0.tgz \
     --set image.tag=0.1.0 \
     --set image.repository=delivery \
     --set dockerregistry=$ACR_SERVER \
     --set "ingress.hosts[0].name=dronedelivery.fabrikam.com" \
     --set "ingress.hosts[0].serviceName=delivery" \
     --set networkPolicy.egress.external.enabled=true \
     --set networkPolicy.egress.external.clusterSubnetPrefix=$CLUSTER_SUBNET_PREFIX \
     --set networkPolicy.ingress.externalSubnet.enabled=true \
     --set networkPolicy.ingress.externalSubnet.subnetPrefix=$GATEWAY_SUBNET_PREFIX \
     --set identity.clientid=$DELIVERY_PRINCIPAL_CLIENT_ID \
     --set identity.resourceid=$DELIVERY_PRINCIPAL_RESOURCE_ID \
     --set cosmosdb.id=$DELIVERY_DATABASE_NAME \
     --set cosmosdb.collectionid=$DELIVERY_COLLECTION_NAME \
     --set keyvault.uri=$DELIVERY_KEYVAULT_URI \
     --set reason="Initial deployment" \
     --set envs.dev=true \
     --namespace backend-dev

**Comment by ckittel** [comment]
That's a good observation, only bash was tested for these instructions.
