### ISSUE TITLE
Proposal - DAPR Adoption

### ISSUE THREAD

**Issue by vimorra** [mspnp/fabrikam-dronedelivery-workload#17]
Hi Team,
are you looking in the option to adopt DAPR as building block for the microservices?
I see the value of this in relation to the "run anywhere" approach that we are willing to have in Azure

Thanks a bunch in advance.

**Comment by ckittel** [comment]
We do not plan on investing time in a dapr implementation at this time.  Going to close this request.  Thank you though for the idea!
