### ISSUE TITLE
CLI script issue

### ISSUE THREAD

**Issue by abhijitkakade914** [mspnp/fabrikam-dronedelivery-workload#8]
We started prerequisites CLI  (in Powershell ISE) script execution step by step. 
 
- Log in to Azure CLI **-- Done**
- Set the resource group variable **-- Done**
- Deploy the workload's prerequisites **-- Done**
- Get the Azure Container Registry and workload resource group name - **Done  -->** This step will return acr resource group name 'rg-shipping-dronedelivery-acr' but in next step you are using this resource group to fetch deployment details. which is wrong. because deployment not done in acr resource group. (We have manually resolved this issue at our end)
- Get the workload user assigned identities **-- Done**
- Deploy the workload -- **Once we start this deployment it get stuck for long time. If we check portal -> resource group -> Deployment -> it dont show any deployment in progress. What is the issue ?**

**Have you faced this issue ?**

![image](https://user-images.githubusercontent.com/46191820/128178636-0c2198ad-68b2-490e-bf1d-618d6ecb96a2.png)

**Comment by ckittel** [comment]
@magrande -- please see the above fourth bullet point and then the sixth.  Any advice to share?

**Comment by magrande** [comment]
@ckittel , @abhijitkakade914

The instructions on the README file are outdated, I'm working on fix now. I'll let you know when this is ready. Thanks for raising this issue

**Comment by magrande** [comment]
Fixed on PR 

https://github.com/mspnp/fabrikam-dronedelivery-workload/pull/10

@abhijitkakade914 Can you please use the updated README ? Let me know if you have issues. Thanks
