### ISSUE TITLE
Code Build error 

### ISSUE THREAD

**Issue by abhijitkakade914** [mspnp/fabrikam-dronedelivery-workload#9]
We are able to manage all prerequisites with some changes in script. but now when we are building image its throwing bellow exception , kindly help to resolve this issue ?

Do we require python installer / setup on machine ?

![image](https://user-images.githubusercontent.com/46191820/128188209-111e39c2-76cb-46ae-9162-b3892215649d.png)

**Comment by ckittel** [comment]
That's an error in your Azure CLI. Can you check to make sure you have the latest version installed?  If you do, I'm not sure where to check next, as that's a failure directly in `az acr build` and doesn't appear to be related to this specific content you're building

**Comment by ckittel** [comment]
Haven't heard back in about two months, will close.  Feel free to reopen though if you would like to continue to provide troubleshooting information.
